/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/db/models/base.py:366: RuntimeWarning: Model 'core.task' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/db/models/base.py:366: RuntimeWarning: Model 'core.task' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
Watching for file changes with StatReloader
Internal Server Error: /tasks/3/complete/
Traceback (most recent call last):
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 233, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 495, in to_internal_value
    for field in fields:
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 378, in _writable_fields
    for field in self.fields.values():
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1103, in get_fields
    field_class, field_kwargs = self.build_field(
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1249, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 1367, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `did_not_finish` is not valid for model `Task` in `core.serializers.TaskCompleteSerializer`.
[31/Jan/2025 04:56:25] "PATCH /tasks/3/complete/ HTTP/1.1" 500 141481
/home/legendarymark/TaskDown/core/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
January 31, 2025 - 04:56:21
Django version 5.1.5, using settings 'taskdown.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/db/models/base.py:366: RuntimeWarning: Model 'core.task' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
Watching for file changes with StatReloader
/home/legendarymark/TaskDown/core/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
January 31, 2025 - 05:03:09
Django version 5.1.5, using settings 'taskdown.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

/home/legendarymark/TaskDown/venv/lib/python3.10/site-packages/django/db/models/base.py:366: RuntimeWarning: Model 'core.task' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
Watching for file changes with StatReloader
